### ISSUE TITLE
Review batch cache clear

### ISSUE THREAD

**Issue by kbens** [psadmin-io/psadmin-plus#109]

**Comment by jpmfv** [comment]
Hey Kyle I forgot to send you more information when I brought this up to you at psadmin.conf this year. but isn't an issue when I run the cache clear on the web or app. just running psa bounce prcs on my windows and linux servers for whatever reason it just does not want to delete the cache folder/files

**Comment by iversond** [comment]
Change this line to rm the directory: https://github.com/psadmin-io/psadmin-plus/blob/master/lib/psadmin_plus.rb#L486

**Comment by kbens** [comment]
This should be fixed in PR #112.
