### ISSUE TITLE
Update gif and wiki

### ISSUE THREAD

**Issue by kbens** [psadmin-io/psadmin-plus#25]
Need some updates to show cli features and new output.

**Comment by iversond** [comment]
Wiki and gif updated, along with a new blog post and podcast about the update.

**Comment by iversond** [comment]
https://psadmin.io/2018/09/25/psadmin-plus-2-0/

**Comment by iversond** [comment]
https://psadmin.io/2018/09/21/151-psadmin_plus-2-0/
