### ISSUE TITLE
Assume PS_HOME\bin or PS_HOME\appserv are in PATH?

### ISSUE THREAD

**Issue by iversond** [psadmin-io/psadmin-plus#55]
Currently, `psa` assumes that the `psadmin` command is in the `PATH` environment variable. Not all systems have that set. Do we want to assume that is a requirement, or do we modify the commands and append the `PS_HOME\bin`/`$env:PS_HOME\appserv` locations before calling `psadmin`?

**Comment by kbens** [comment]
We append it. I had that in bash/poweshell, so we should do same here.
